apiVersion: v1
kind: Service
metadata:
  name: postgres   # MUST match API DB_HOST

spec:
  selector:
    app: postgres

  type: ClusterIP

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432